### ISSUE TITLE
Installing “-project-shell-env@0.2.4” failed.

### ISSUE THREAD

**Issue by zimbatm** [ddiachkov/atom-project-shell-env#2]
Hi, direnv author here. I tried installing your plugin but got this error, any idea what the cause would be ? It's a bit weird that the install is looking for a package.json in my home.

```
npm ERR! install Couldn't read dependencies
npm ERR! Linux 4.4.0
npm ERR! argv "/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app/apm/bin/node" "/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/zimbatm/.atom/.apm/.apmrc" "--userconfig" "/home/zimbatm/.atom/.apmrc" "install" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! path /home/zimbatm/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34

npm ERR! package.json ENOENT, open '/home/zimbatm/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/zimbatm/npm-debug.log
```

content of npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app/apm/bin/node',
1 verbose cli   '/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/home/zimbatm/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/home/zimbatm/.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   '--target=0.34.5',
1 verbose cli   '--arch=x64' ]
2 info using npm@2.13.3
3 info using node@v0.10.40
4 verbose readDependencies loading dependencies from /home/zimbatm/package.json
5 error install Couldn't read dependencies
6 verbose stack Error: ENOENT, open '/home/zimbatm/package.json'
7 verbose cwd /home/zimbatm
8 error Linux 4.4.0
9 error argv "/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app/apm/bin/node" "/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/zimbatm/.atom/.apm/.apmrc" "--userconfig" "/home/zimbatm/.atom/.apmrc" "install" "--target=0.34.5" "--arch=x64"
10 error node v0.10.40
11 error npm  v2.13.3
12 error path /home/zimbatm/package.json
13 error code ENOPACKAGEJSON
14 error errno 34
15 error package.json ENOENT, open '/home/zimbatm/package.json'
15 error package.json This is most likely not a problem with npm itself.
15 error package.json npm can't find a package.json file in your current directory.
16 verbose exit [ 34, true ]
```

**Comment by ddiachkov** [comment]
Hi! I think this is problem with leading dash in package name.
Please try this command: `apm install "\-project-shell-env@0.2.4"`

**Comment by zimbatm** [comment]
Yep that's it.

I then started atom and tried to go into the preference pane. It didn't respond for a while and then asked me if I wanted to continue executing the script. Then I restarted atom, now it's showing the preference pane but if I navigate into "packages" it keeps "Loading packages..." indefinitely.

Maybe the package could be renamed `000-project-shell-env` to avoid the leading dash.

**Comment by ddiachkov** [comment]
Do you have something like oh-my-zsh that slows down shell start?

Please open atom in dev mode (`atom --dev`) and show me dev tool's console output (View →  Developer → Toggle Developer Tools).

> Maybe the package could be renamed 000-project-shell-env to avoid the leading dash.

Yeah, this is a good idea!

**Comment by zimbatm** [comment]
I'm running bash without a framework. No fancy PS1. I just have a couple of hooks installed: termite, autojump and direnv.

It looks like atom doesn't find libgtk2 which might well be a nixos packaging issue. The last 3 lines appeared when I went to Preferences -> Packages

```
$ atom -d -f
[26654:0210/121729:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[26654:0210/121729:ERROR:browser_main_loop.cc(217)] GTK theme error: Unable to locate theme engine in module_path: "adwaita",
[26654:0210/121729:ERROR:browser_main_loop.cc(217)] GTK theme error: Unable to locate theme engine in module_path: "adwaita",
[26654:0210/121729:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[26654:0210/121729:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[26654:0210/121729:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[26654:0210/121729:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[26686:0210/121729:ERROR:renderer_main.cc(200)] Running without renderer sandbox
auto-updater is not implemented on this platform
Error: auto-updater is not implemented on this platform
    at Object.<anonymous> (/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:11:13)
    at Object.<anonymous> (/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:14:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at AutoUpdateManager.module.exports.AutoUpdateManager.setupAutoUpdater (/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app.asar/src/browser/auto-update-manager.js:51:23)
    at /nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app.asar/src/browser/auto-update-manager.js:42:24
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
    at NavigationController.loadUrl (/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/atom.asar/browser/api/lib/navigation-controller.js:59:24)
    at EventEmitter.webContents.(anonymous function) [as loadUrl] (/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/atom.asar/browser/api/lib/web-contents.js:81:27)
    at BrowserWindow.loadUrl (/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/atom.asar/browser/api/lib/browser-window.js:121:37)
    at AtomWindow.module.exports.AtomWindow.setLoadSettings (/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app.asar/src/browser/atom-window.js:124:33)
    at new AtomWindow (/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app.asar/src/browser/atom-window.js:110:12)
    at AtomApplication.module.exports.AtomApplication.openPaths (/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app.asar/src/browser/atom-application.js:686:24)
    at AtomApplication.module.exports.AtomApplication.openWithOptions (/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app.asar/src/browser/atom-application.js:132:21)
    at AtomApplication.module.exports.AtomApplication.loadState (/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app.asar/src/browser/atom-application.js:770:16)
    at new AtomApplication (/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app.asar/src/browser/atom-application.js:114:14)
    at createAtomApplication (/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app.asar/src/browser/atom-application.js:60:16)
    at Function.module.exports.AtomApplication.open (/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app.asar/src/browser/atom-application.js:63:9)
    at EventEmitter.<anonymous> (/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app.asar/src/browser/main.js:55:23)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
App load time: 566ms
[26654:0210/121730:INFO:CONSOLE(15)] "[project-shell-env]", source: /home/zimbatm/.atom/packages/-project-shell-env/lib/project-shell-env.coffee (15)
[26654:0210/121730:INFO:CONSOLE(15)] "[project-shell-env]", source: /home/zimbatm/.atom/packages/-project-shell-env/lib/project-shell-env.coffee (15)
[26654:0210/121731:INFO:CONSOLE(15)] "[project-shell-env]", source: /home/zimbatm/.atom/packages/-project-shell-env/lib/project-shell-env.coffee (15)
[26654:0210/121731:INFO:CONSOLE(15)] "[project-shell-env]", source: /home/zimbatm/.atom/packages/-project-shell-env/lib/project-shell-env.coffee (15)
[26654:0210/121731:INFO:CONSOLE(15)] "[project-shell-env]", source: /home/zimbatm/.atom/packages/-project-shell-env/lib/project-shell-env.coffee (15)
[26654:0210/121731:INFO:CONSOLE(15)] "[project-shell-env]", source: /home/zimbatm/.atom/packages/-project-shell-env/lib/project-shell-env.coffee (15)
[26654:0210/121731:INFO:CONSOLE(15)] "[project-shell-env]", source: /home/zimbatm/.atom/packages/-project-shell-env/lib/project-shell-env.coffee (15)
[26654:0210/121731:INFO:CONSOLE(15)] "[project-shell-env]", source: /home/zimbatm/.atom/packages/-project-shell-env/lib/project-shell-env.coffee (15)
[26654:0210/121731:INFO:CONSOLE(15)] "[project-shell-env]", source: /home/zimbatm/.atom/packages/-project-shell-env/lib/project-shell-env.coffee (15)
[26654:0210/121731:INFO:CONSOLE(52)] "Window load time: 1620ms", source: file:///nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app.asar/static/index.js (52)
[26654:0210/121731:INFO:CONSOLE(0)] "/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
[26654:0210/121732:INFO:CONSOLE(91)] "/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/atom: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
", source: /nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app.asar/src/task.js (91)
[26654:0210/121732:INFO:CONSOLE(138)] "Fetching local packages failed.", source: /nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app.asar/node_modules/settings-view/lib/main.js (138)
[26654:0210/121831:INFO:CONSOLE(91)] "/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/atom: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
", source: /nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app.asar/src/task.js (91)
[26654:0210/121841:INFO:CONSOLE(0)] "::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
[26654:0210/121846:INFO:CONSOLE(91)] "/nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/atom: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
", source: /nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app.asar/src/task.js (91)
[26654:0210/121852:INFO:CONSOLE(298)] "Fetching local packages failed.", source: /nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js (298)
[26654:0210/121852:INFO:CONSOLE(299)] "Uncaught (in promise) TypeError: Cannot read property 'hide' of undefined", source: /nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js (299)
[26654:0210/121852:INFO:CONSOLE(177)] "Uncaught (in promise) Error: Fetching outdated packages and themes failed.", source: /nix/store/99jqgk3pf56xflhiag7w7hj8zm88jggj-atom-1.4.3/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js (177)
```

**Comment by ddiachkov** [comment]
Ok, I was able to reproduce this error.
1. -project-shell-env rewrites atom's LD_LIBRARY_PATH from `/nix/store/blah-blah-atom/lib:blah-blah` to default path.
2. Then atom runs apm binary to list installed packages.
3. Apm process inherits parent environment and fails because it can't find libstdc++.

I shall add LD_LIBRARY_PATH to the blacklist.

**Comment by ddiachkov** [comment]
Please try a new version.

`apm uninstall -project-shell-env && apm install 000-project-shell-env@0.3.0`

**Comment by zimbatm** [comment]
Great, all good now. I had to add `--` between `apm uninstall` and
`-project-shell-env` because it was interpreting the latter as a
command-line opt. It's probably a good thing you renamed the project.

If you want deeper integration with direnv let me know. I can add a `direnv
export json` output to get environment changes. Then you don't even need to
invoke bash anymore.

**Comment by ddiachkov** [comment]
JSON export would be awesome! Though I am not sure how to integrate this functionality to project-shell-env. So I think I'll create new 000-atom-direnv package that will run `direnv export` and also will include direnv specific commands like direnv:allow and direnv:edit.

**Comment by zimbatm** [comment]
So I finally got around and added the `direnv export json` functionality over here: https://github.com/direnv/direnv/pull/209
do you want to give it a go and give me some feedback if the export format is good for you ?
